# Generated by Django 2.0.7 on 2018-07-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
    ]
